[book]
authors = ["rsteube"]
language = "en"
multilingual = false
src = "src"
title = "carapace-spec"

[output.html]
default-theme = "Mocha"
additional-css = ["asciinema/asciinema-player.css", "./theme/catppuccin.css", "./theme/catppuccin-highlight.css"]
additional-js = ["asciinema/asciinema-player.min.js", "asciinema/load.js"]
git-repository-url = "https://github.com/rsteube/carapace-spec"
edit-url-template = "https://github.com/rsteube/carapace-spec/edit/master/docs/{path}"

#[output.linkcheck]
